### ISSUE TITLE
Doesn't start on Ubuntu 16.04: ImportError: No module named cairo

### ISSUE THREAD

**Issue by burgerga** [stuartlangridge/ColourPicker#12]
The whole error message is:

```
/usr/lib/python2.7/dist-packages/pick/__main__.py:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, GLib, GdkPixbuf, Gio
/usr/lib/python2.7/dist-packages/pick/__main__.py:3: PyGIWarning: Unity was imported without specifying a version first. Use gi.require_version('Unity', '7.0') before import to ensure that the right version gets loaded.
  from gi.repository import Unity
Traceback (most recent call last):
  File "/usr/bin/pick-colour-picker", line 9, in <module>
    load_entry_point('pick-colour-picker==1.0', 'gui_scripts', 'pick-colour-picker')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/pick/__main__.py", line 6, in <module>
    import cairo, math, json, os, codecs, time, subprocess, sys
ImportError: No module named cairo
```

Installing `python-cairo` lets it start, so maybe this should be added as dependency.

**Comment by stuartlangridge** [comment]
Should be fixed in version 1.2, which I had already built for Ubuntu 14.04 but I had an older version of Pick available for 16.04. The PPA should now be up to date; if version 1.2 doesn't fix this, please re-open.
