### ISSUE TITLE
Can't pick colors on Ubuntu Gnome 16.04

### ISSUE THREAD

**Issue by burgerga** [stuartlangridge/ColourPicker#13]
The main window disappears but the magnifier doesn't appear

```
/usr/lib/python2.7/dist-packages/pick/__main__.py:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, GLib, GdkPixbuf, Gio
/usr/lib/python2.7/dist-packages/pick/__main__.py:3: PyGIWarning: Unity was imported without specifying a version first. Use gi.require_version('Unity', '7.0') before import to ensure that the right version gets loaded.
  from gi.repository import Unity
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pick/__main__.py", line 1178, in finish_loading_history
    success, contents, _ = f.load_contents_finish(res)
GLib.Error: g-io-error-quark: Error opening file: No such file or directory (1)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pick/__main__.py", line 961, in set_magnifier_cursor
    Gdk.cairo_set_source_pixbuf(base_context, scaled_pb_subset, 0, 0)
KeyError: 'could not find foreign type Context'
```

**Comment by stuartlangridge** [comment]
Should be fixed in version 1.2, which I had already built for Ubuntu 14.04 but I had an older version of Pick available for 16.04. The PPA should now be up to date; if version 1.2 doesn't fix this, please re-open.
