### ISSUE TITLE
cannot import name GTK

### ISSUE THREAD

**Issue by gsouf** [stuartlangridge/ColourPicker#42]
Hi,

Just installed the package through the PPA and when I run ``pick-colour-picker`` I got this issue:

```
Traceback (most recent call last):
  File "/usr/bin/pick-colour-picker", line 9, in <module>
    load_entry_point('pick-colour-picker==1.0', 'gui_scripts', 'pick-colour-picker')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/pick/__main__.py", line 1, in <module>
    from gi.repository import Gtk, Gdk, GLib, GdkPixbuf, Gio
ImportError: cannot import name Gtk
```

I'm probably missing a gtk thing, or python thing but I cannot figure out what exactly.

**Comment by gsouf** [comment]
Well, I've had to install package ``gir1.2-gtk-3.0``. I think it should be listed in dependencies in the ppa, shouldn't it?

**Comment by stuartlangridge** [comment]
Yes, it should. I'll have a look at fixing that.

**Comment by stuartlangridge** [comment]
If you install the snap version, that should fix this problem entirely.
