### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by stuartlangridge** [stuartlangridge/ColourPicker#57]
because python 2 is going away, and it's the right thing to do.

**Comment by stuartlangridge** [comment]
Code work done in https://github.com/stuartlangridge/ColourPicker/commit/fb980ca3193bc33540d6983bc4c71e8cd6743065 but the snap needs to change to use python3 instead too, and probably setup.py as well.

**Comment by flexiondotorg** [comment]
While migrating the packaging to Python 3.x I encountered this.
```
Traceback (most recent call last):
  File "/snap/pick-colour-picker/x13/lib/python3.6/site-packages/pick/__main__.py", line 763, in magnifier_move
    self.set_magnifier_cursor()
  File "/snap/pick-colour-picker/x13/lib/python3.6/site-packages/pick/__main__.py", line 477, in set_magnifier_cursor
    col = self.get_colour_from_pb(self.latest_pb)
  File "/snap/pick-colour-picker/x13/lib/python3.6/site-packages/pick/__main__.py", line 758, in get_colour_from_pb
    rgb_vals = tuple([ord(x) for x in pixel_data[offset:offset+3]])
TypeError: slice indices must be integers or None or have an __index__ method
```

**Comment by stuartlangridge** [comment]
Now fixed and subsidiary work on setup.py etc also done in https://github.com/stuartlangridge/ColourPicker/commit/44c1a89c66959e7013685234394c2748507b19bc by @flexiondotorg.
